source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxCoreMotion_Example' do
  platform :ios, '8.0'
  pod 'RxCoreMotion', :path => '../'
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
 end

target 'RxCoreMotion_Tests' do
  pod 'RxTest'
end



post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    # Configure Pod targets for Xcode 8 compatibility
    config.build_settings['SWIFT_VERSION'] = '3.0'
    config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
  end
end
