source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxCoreMotion_Example' do
  platform :ios, '8.0'
  pod 'RxCoreMotion', :path => '../'
  pod 'RxSwift', '~> 3.3'
  pod 'RxCocoa', '~> 3.3'
 end

target 'RxCoreMotion_Tests' do
  pod 'RxTest'
end
