source 'https://github.com/CocoaPods/Specs.git'
project 'RxCoreMotionCocoapodsExample.xcodeproj'
platform :ios, '9.0'

target 'RxCoreMotionExample' do
  use_frameworks!
  pod 'RxCoreMotion', :path => '../'
end
