source 'https://github.com/CocoaPods/Specs.git'
project 'RxCoreMotionCocoapodsExample.xcodeproj'
platform :ios, '8.0'

target 'RxCoreMotionExample' do
  use_frameworks!

  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxCoreMotion', :path => '../'
end
